name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: my-step1
      - uses: actions/checkout@v3
      - name: Run a simple Github Action
        run: echo "Hello World! this worksflow run successfully for this particul;ar action"
